[package]
name = "space_shooter"
version = "0.1.0"
authors = ["trsoluti <thomas_odell@trsolutions.biz>"]

[dependencies]
#amethyst = { path = "../../../Rust/amethyst" }
lazy_static = "1.0"
rand = "0.3"
serde = "1.0.24"
serde_derive = "1.0"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst"
rev = "e6e1d27640f46c5dabbbb22d77ff1bdd4f3fa106"