[package]
name = "space_shooter"
version = "0.1.0"
authors = ["trsoluti <thomas_odell@trsolutions.biz>"]

[dependencies]
#amethyst = { path = "../../../Rust/amethyst" }
lazy_static = "1.0"
rand = "0.3"
serde = "1.0.24"
serde_derive = "1.0"
gfx_core = "*"
gfx = "*"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst"
rev = "ba233ed"
